[params]
[params.BluestNight]
[params.BluestNight.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[params.BluestNight.fonts]
    header_style = "sans-serif"
    body_style = "sans-serif"
    print_header_style = "sans-serif"
    print_body_style = "serif"

[params.BluestNight.sidebar]
    [params.BluestNight.sidebar.categories]
        path = "sidebar/widgets/categories/widget.html"
        cache = true
    [params.BluestNight.sidebar.coinhive]
        path = "sidebar/widgets/coinhive/widget.html"
        js = "sidebar/widgets/coinhive/js.html"
        cache = true
    [params.BluestNight.sidebar.events]
        path = "sidebar/widgets/events/widget.html"
        cache = true
    [params.BluestNight.sidebar.patreon]
        path = "sidebar/widgets/patreon/widget.html"
        cache = true
    [params.BluestNight.sidebar.recent]
        path = "sidebar/widgets/recent/widget.html"
    [params.BluestNight.sidebar.search]
        path = "sidebar/widgets/search/widget.html"
        js = "sidebar/widgets/search/js.html"
        css = "sidebar/widgets/search/css.html"
        cache = true
    [params.BluestNight.sidebar.taglist]
        path = "sidebar/widgets/taglist/widget.html"
        cache = true

[mediaTypes]
    [mediaTypes."netlify/headers"]
        suffix = ""

[outputFormats]
    [outputFormats.NetlifyHeaders]
        isPlainText = true
        basename = "_headers"
        mediaType = "netlify/headers"
        notAlternative = true
