baseurl = "http://hugo.spf13.com/"
title = "BluestNight"
author = "Michael Bryant"
canonifyurls = true
paginate = 3
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "A configurable dark theme with blue accents for Hugo"
    description = "Here is a description of my site that will appear in search engine results - W00t!" # Description of your site
    authorbox = true
    author = "Some Guy"
    post_navigation = false

[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = true
    tags_counter = true
    patreon = "shadow53"

[Params.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[Params.social]
    gitlab = "Shadow53/BluestNight"

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 1
    identifier = "docs"
    url = "#"
    [[menu.main]]
      name = "Pages"
      weight = 1
      parent = "docs"
      identifier = "docs-pages"
      url = "#"
    [[menu.main]]
      name = "Shortcodes"
      weight = 1
      parent = "docs"
      identifier = "docs-shortcodes"
      url = "#"
    [[menu.main]]
      name = "Sidebar"
      weight = 1
      parent = "docs"
      identifier = "docs-sidebar"
      url = "#"
    [[menu.main]]
      name = "Site"
      weight = 1
      parent = "docs"
      identifier = "docs-site"
      url = "#"
    [[menu.main]]
      name = "Example Config"
      weight = 1
      parent = "docs"
      identifier = "docs-example-config"
      url = "/BluestNight/config.toml.example"
  [[menu.main]]
    name = "Tutorials"
    weight = 10
    identifier = "tutorials"
    url = "#"
